version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.node
    ports:
      - "3000:3000"
    command: yarn dev
    environment:
      NODE_ENV: development
    volumes:
      - .:/home/node/app